const MongoDbUrl = "mongodb+srv://sam:sky@trial.wcv96nz.mongodb.net/Authentication?retryWrites=true&w=majority";
const usersCollection = "Users";
const userNameCollection = "Username";
const defaultItinerariesCollection = "DefaultItineraries";
const verifiedItinerariesCollection = "VerifiedItineraries";
const usersItinerariesCollection = "UsersItineraries";
const systemDataCollection = "SystemData";
const itineraryInformationCollection = "ItinerariesInformation";
const countriesAndRegionsCollection = "CountriesAndRegions";